### ISSUE TITLE
How can I solve this problem? thank you.

### ISSUE THREAD

**Issue by dudu-777** [ktr-hubrt/MPN#33]
0%|          | 0/120 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:/Project/MPN/Train.py", line 134, in <module>
    for j, (imgs) in enumerate(train_batch):
  File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Project\MPN\model\utils.py", line 144, in __getitem__
    frame_ind = random.sample(range(0, length//self.num_segs), 1)
  File "C:\ProgramData\Anaconda3\envs\MPN\lib\random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
  0%|          | 0/120 [00:00<?, ?it/s]

Many thanks in advance.

**Comment by dudu-777** [comment]
为什么 我在ped2数据集跑出来只有44.5

**Comment by lllyua** [comment]
> 0%| | 0/120 [00:00<?, ?it/s]Traceback (most recent call last): File "D:/Project/MPN/Train.py", line 134, in for j, (imgs) in enumerate(train_batch): File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 521, in **next** data = self._next_data() File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Project\MPN\model\utils.py", line 144, in **getitem** frame_ind = random.sample(range(0, length//self.num_segs), 1) File "C:\ProgramData\Anaconda3\envs\MPN\lib\random.py", line 320, in sample raise ValueError("Sample larger than population or is negative") ValueError: Sample larger than population or is negative 0%| | 0/120 [00:00<?, ?it/s]
> 
> Many thanks in advance.

估摸着num_worker那里不对劲

**Comment by sskacmakc** [comment]
你解决了吗，怎么把数据集中的训练集放到frames文件夹下面呀

**Comment by rayyyy122** [comment]
> 0%| | 0/120 [00:00<?, ?it/s]Traceback (most recent call last): File "D:/Project/MPN/Train.py", line 134, in for j, (imgs) in enumerate(train_batch): File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 521, in **next** data = self._next_data() File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Project\MPN\model\utils.py", line 144, in **getitem** frame_ind = random.sample(range(0, length//self.num_segs), 1) File "C:\ProgramData\Anaconda3\envs\MPN\lib\random.py", line 320, in sample raise ValueError("Sample larger than population or is negative") ValueError: Sample larger than population or is negative 0%| | 0/120 [00:00<?, ?it/s]
> 
> Many thanks in advance.

您好，请问这个问题怎么解决的啊？

**Comment by sskacmakc** [comment]
数据集路径没写对
















At 2024-11-01 08:53:39, "Dingrui(Ray) Tao" ***@***.***> wrote:

0%| | 0/120 [00:00<?, ?it/s]Traceback (most recent call last): File "D:/Project/MPN/Train.py", line 134, in for j, (imgs) in enumerate(train_batch): File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 521, in next data = self._next_data() File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\ProgramData\Anaconda3\envs\MPN\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Project\MPN\model\utils.py", line 144, in getitem frame_ind = random.sample(range(0, length//self.num_segs), 1) File "C:\ProgramData\Anaconda3\envs\MPN\lib\random.py", line 320, in sample raise ValueError("Sample larger than population or is negative") ValueError: Sample larger than population or is negative 0%| | 0/120 [00:00<?, ?it/s]

Many thanks in advance.

您好，请问这个问题怎么解决的啊？
